orientation: normal
rows: 4
columns: 3
knobs: 2
layers:
- buttons:
  - - escape
    - favorites
    - s
  - - f13
    - f13
    - cmd-shift-f
  - - ctrl-grave
    - cmd-a
    - left
  - - down
    - right
    - f17
  knobs:
  - cw: volumeup
    ccw: volumedown
    press: mute
  - cw: next
    ccw: previous
    press: play
